" Make external commands work through a pipe instead of a pseudo-tty
"set noguipty

" You can also specify a different font, overriding the default font
"if has('gui_gtk2')
"  set guifont=Bitstream\ Vera\ Sans\ Mono\ 12
"else
"  set guifont=-misc-fixed-medium-r-normal--14-130-75-75-c-70-iso8859-1
"endif

" If you want to run gvim with a dark background, try using a different
" colorscheme or running 'gvim -reverse'.
" http://www.cs.cmu.edu/~maverick/VimColorSchemeTest/ has examples and
" downloads for the colorschemes on vim.org

" Source a global configuration file if available
if filereadable("/etc/vim/gvimrc.local")
  source /etc/vim/gvimrc.local
endif

source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
set nocompatible            "不使用与vi兼容的键盘模式
set autoindent              " 打开自动缩进
set shiftwidth=4            " 自动缩进4个空格

set tabstop=4               " Tab宽度等于4个空格的宽度
set expandtab               " Tab用空格替换

set cursorline              " 突出显示当前行
set nu!                     " 显示行号
set showmatch               " 显示括号配对情况

set foldmethod=indent       " 更多的缩进标识更高级的折叠
set foldlevel=100           " 禁止自动折叠

colorscheme desert          " desert配色方案
syntax enable               " 语法高亮
syntax on                   " 开启文件类型检测
set nobackup                " 无备份文件

set laststatus=2            " 开启状态栏信息
set showcmd                 " 在窗口右下角打开命令提示
" 每行超过80个的字符用下划线标示
au BufRead,BufNewFile *.h,*.asm,*.c,*.cpp,*.java,*.cs,*.sh,*.lua,*.pl,*.pm,*.py,*.rb,*.hs,*.vim 2match Underlined /.\%82v/

" 设置字体编码
set enc=utf-8
set fencs=utf-8,ucs-bom,shift-jis,gb108030,gbk,gb2312,cp936
set helplang=cn
set encoding=utf8
set langmenu=zh_CN.UTF-8
set imcmdline

" 解决菜单乱码
source $VIMRUNTIME/menu.vim
source $VIMRUNTIME/delmenu.vim

" 解决consle输出乱码
" language message zh_CN.utf-8

" 文件管理器插件NERD_tree
let NERDTreeWinPos='left'
let NERDTreeWinSize=31
let NERDTreeChDirMode=1


